
set search_path TO public;

CREATE TABLE message_type (
    id   SMALLINT       NOT NULL PRIMARY KEY,
    name VARCHAR(255)   NOT NULL
);

INSERT INTO message_type (id, name) VALUES (0, 'ASSISTANT');
INSERT INTO message_type (id, name) VALUES (1, 'USER');

CREATE TABLE message (
    id          INT8         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id     SMALLINT     NOT NULL REFERENCES message_type (id),
    user_id     INT8         NOT NULL REFERENCES app_user (id),
    content     VARCHAR(255) NOT NULL DEFAULT '',
    time        TIMESTAMP    NOT NULL DEFAULT now()
);
