
set search_path TO public;

CREATE TABLE notification (
    id          INT8        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INT8        NOT NULL REFERENCES app_user (id),
    last_sent   TIMESTAMPTZ NOT NULL DEFAULT now()
);
