
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Pull Request

on: workflow_call

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.6.1
          cache: 'npm'
          cache-dependency-path: reactjs/package-lock.json

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
