
name: Build Pull Request

on:
  workflow_call:
    inputs:
      upload-artifact:
        required: true
        type: boolean
      gradle-args:
        required: false
        type: string
        default:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.6.1
          cache: 'npm'
          cache-dependency-path: reactjs/package-lock.json

      # When using setup-gradle they recommend to avoid using other mechanisms to save and restore Gradle User Home
      # Specifically:
      #    Avoid using actions/cache configured to cache the Gradle User Home
      #    Avoid using actions/setup-java with the cache: gradle option
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

#      - name: Setup Gradle to publish build scans
#        uses: gradle/actions/setup-gradle@v3
#        with:
#          build-scan-publish: true
#          build-scan-terms-of-service-url: "https://gradle.com/terms-of-service"
#          build-scan-terms-of-service-agree: "yes"


      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
#          arguments: ${{ inputs.gradle-args }} build
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
#        if: ${{ inputs.upload-artifact }}
        with:
          name: Build Artifacts
          path: server/build

      - name: Upload Project Page
        uses: actions/upload-pages-artifact@v3
        if: ${{ inputs.upload-artifact }}
        with:
          path: server/build/reports
