
name: Build Pull Request

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    steps:
      - name: Reusable Setup and Build
        uses: ./.github/workflows/setup-and-build.yml
