
name: Build Pull Request

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Reusable Setup and Build
        uses: ./.github/workflows/build-and-test.yml
