
name: Build On PR

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  steps:
    - name: Checkout
      uses: actions/checkout@v3
#  build:
#    uses: ./.github/workflows/build-and-test.yml
