
name: Build On PR

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      upload-artifact: false
      # gradle-args: -x test -x integrationTest
