
name: Build On PR

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository first, otherwise the workflow won't be able to see the other action
      - name: Checkout
        uses: actions/checkout@v3

      - name: Reusable Setup and Build
        uses: ./.github/workflows/build-and-test.yml
