
name: Build Pull Request

on:
  workflow_call:
    inputs:
      upload-artifact:
        required: true
        type: boolean
      gradle-args:
        required: false
        type: string
        default:

permissions:
  contents: read

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.6.1
          cache: 'npm'
          cache-dependency-path: reactjs/package-lock.json

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ${{ inputs.gradle-args }} build pageBundle

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.upload-artifact }}
        with:
          name: Build Artifacts
          path: server/build/libs/server.jar
