
name: Build Pull Request

on:
  workflow_call:
    inputs:
      upload-artifact:
        required: true
        type: boolean
      gradle-args:
        required: false
        type: string
        default:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.6.1
          cache: 'npm'
          cache-dependency-path: reactjs/package-lock.json

      # read docs carefully: https://github.com/gradle/actions/tree/main/setup-gradle
      # don't use cache-gradle from setup-java
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build
        # ${{ inputs.gradle-args }} build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.upload-artifact }}
        with:
          name: Build Artifacts
          path: server/build/libs/server.jar

      - name: Upload Project Page
        uses: actions/upload-pages-artifact@v3
        if: ${{ inputs.upload-artifact }}
        with:
          path: server/build/reports
