
name: Build On PR

on:
  pull_request:
    branches: [ "master" ]
    inputs:
      upload-artifact:
        description: 'Upload artifact after build'
        required: true
        type: boolean
        default: true

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      upload-artifact: ${{github.event.inputs.upload-artifact}}
      # gradle-args: -x test -x integrationTest
