
name: Build and Deploy

#on:
#  push:
#    branches: [ "master" ]

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
      uses: ./.github/workflows/build-and-test.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact from Build
        uses: actions/download-artifact@v3
        with:
          name: Server Jar
          path: server/build/libs

#      - name: Login to Heroku
#        uses: akhileshns/heroku-deploy@v3.12.14
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "stage"
#          heroku_email: "thinkbigthings@gmail.com"
#          justlogin: true
#
#      - name: Deploy to Staging
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: -Papp=stage deployHeroku
