
name: Build and Deploy

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:
      uses: ./.github/workflows/build-and-test.yml
      with:
        upload-artifact: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      # heroku deployment needs git to be present
      # and setup-java needs gradle to detect toolchains for downloads
      - name: Checkout
        uses: actions/checkout@v3

      # gradle needs Java
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Download Artifact from Build
        uses: actions/download-artifact@v3
        with:
          name: Build Artifacts
          path: server/build/libs

      # Debugging
      - name: List Downloaded Files
        run: |
          ls -alrt server/build/libs

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stage"
          heroku_email: "thinkbigthings@gmail.com"
          justlogin: true

      - name: Deploy to Staging
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -Papp=stage deployHeroku
