
name: Build and Deploy

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write
  pages: write

jobs:

  build:
      uses: ./.github/workflows/build-and-test.yml
      with:
        upload-artifact: true
        # tests were run on PR, so skip them here
        # gradle-args: -x test -x integrationTest

  deploy-project-page:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  deploy-heroku-staging:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # files from other jobs are not available to other jobs
      # heroku deployment needs git to be present so download that here
      - name: Checkout
        uses: actions/checkout@v4

      # We upload to Heroku using the heroku gradle plugin
      # which needs gradle, which needs Java, so we need to download Java here
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Download Artifact from Build
        uses: actions/download-artifact@v4
        with:
          name: Build Artifacts
          path: server/build/libs

      # Debugging
      - name: List Downloaded Files
        run: |
          ls -alrt server/build/libs

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stage"
          heroku_email: "thinkbigthings@gmail.com"
          justlogin: true

      - name: Deploy to Staging
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: -Papp=stage deployHeroku
