
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "dynamic-cert" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
          cache: 'npm'
          cache-dependency-path: reactjs/package-lock.json

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stage"
          heroku_email: "jay@levelstonesoftware.com"
          justlogin: true

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: genKey build

      - name: Deploy to Staging
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -Papp=stage deployHeroku
