
name: Start CD

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write
  pages: write

jobs:

  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      save-artifacts-for-deployment: true

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
