
name: Build On PR

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write
  pages: write

jobs:

  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      save-artifacts-for-deployment: false
