
name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  READY_FOR_DEPLOYMENT: ${{ github.event_name != 'pull_request' }}

permissions:
  contents: read
  id-token: write
  pages: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.6.1
          cache: 'npm'
          cache-dependency-path: reactjs/package-lock.json

      # read docs carefully: https://github.com/gradle/actions/tree/main/setup-gradle
      # don't use cache-gradle from setup-java
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{env.READY_FOR_DEPLOYMENT}}
        with:
          name: Build Artifacts
          path: server/build/libs/server.jar

      - name: Upload Project Page
        uses: actions/upload-pages-artifact@v3
        if: ${{env.READY_FOR_DEPLOYMENT}}
        with:
          path: server/build/reports



  deploy-project-page:
    if: ${{env.READY_FOR_DEPLOYMENT}}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  deploy-heroku-staging:
    if: ${{env.READY_FOR_DEPLOYMENT}}
    needs: build
    runs-on: ubuntu-latest

    steps:
      # files from other jobs are not available to other jobs
      # heroku deployment needs git to be present so download that here
      - name: Checkout
        uses: actions/checkout@v4

      # We upload to Heroku using the heroku gradle plugin
      # which needs gradle, which needs Java, so we need to download Java here
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Download Artifact from Build
        uses: actions/download-artifact@v4
        with:
          name: Build Artifacts
          path: server/build/libs

      # Debugging
      - name: List Downloaded Files
        run: |
          ls -alrt server/build/libs

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stage"
          heroku_email: "thinkbigthings@gmail.com"
          justlogin: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Deploy to Staging
        run: ./gradlew -Papp=stage deployHeroku
